base: synthetic_d10
vary:
  - {sigma: 0.25, sigma_u: 0.25}
  - {sigma: 0.25, sigma_u: 0.5}
  - {sigma: 0.25, sigma_u: 1.0}
  - {sigma: 0.25, sigma_u: 0.1}
  - {sigma: 0.25, sigma_u: 0.05}
  - {sigma: 0.5, sigma_u: 0.25}
  - {sigma: 0.5, sigma_u: 0.5}
  - {sigma: 0.5, sigma_u: 1.0}
  - {sigma: 0.5, sigma_u: 0.1}
  - {sigma: 0.5, sigma_u: 0.05}
  - {sigma: 1.0, sigma_u: 0.25}
  - {sigma: 1.0, sigma_u: 0.5}
  - {sigma: 1.0, sigma_u: 1.0}
  - {sigma: 1.0, sigma_u: 0.1}
  - {sigma: 1.0, sigma_u: 0.05}
  - {sigma: 0.1, sigma_u: 0.25}
  - {sigma: 0.1, sigma_u: 0.5}
  - {sigma: 0.1, sigma_u: 1.0}
  - {sigma: 0.1, sigma_u: 0.1}
  - {sigma: 0.1, sigma_u: 0.05}
  - {sigma: 0.05, sigma_u: 0.25}
  - {sigma: 0.05, sigma_u: 0.5}
  - {sigma: 0.05, sigma_u: 1.0}
  - {sigma: 0.05, sigma_u: 0.1}
  - {sigma: 0.05, sigma_u: 0.05}