base: d20
vary:
  - {s_A: 1, s_B: 1}
  - {s_A: 2, s_B: 1}
  - {s_A: 3, s_B: 1}
  - {s_A: 4, s_B: 1}
  - {s_A: 4, s_B: 2}
  - {s_A: 5, s_B: 2}
  - {s_A: 6, s_B: 2}
  - {s_A: 7, s_B: 2}
  - {s_A: 8, s_B: 2}
  - {s_A: 8, s_B: 3}
  - {s_A: 9, s_B: 3}
  - {s_A: 10, s_B: 3}
  - {s_A: 11, s_B: 3}
  - {s_A: 12, s_B: 3}
  - {s_A: 12, s_B: 3}
  - {s_A: 12, s_B: 4}
  - {s_A: 13, s_B: 4}
  - {s_A: 14, s_B: 4}
  - {s_A: 15, s_B: 4}
  - {s_A: 16, s_B: 4}
