base: sparsity
vary:
  - {name: s2,  s_A: 1,  s_B: 1}
  - {name: s4,  s_A: 3,  s_B: 1}
  - {name: s6,  s_A: 5,  s_B: 1}
  - {name: s8,  s_A: 7,  s_B: 1}
  - {name: s10, s_A: 9,  s_B: 1}
  - {name: s12, s_A: 11, s_B: 1}
  - {name: s14, s_A: 13, s_B: 1}
  - {name: s16, s_A: 15, s_B: 1}
  - {name: s18, s_A: 17, s_B: 1}
  - {name: s20, s_A: 19, s_B: 1}
  - {name: s22, s_A: 21, s_B: 1}
  - {name: s24, s_A: 23, s_B: 1}
  - {name: s26, s_A: 25, s_B: 1}
  - {name: s28, s_A: 27, s_B: 1}
  - {name: s30, s_A: 29, s_B: 1}
  - {name: s32, s_A: 31, s_B: 1}
  - {name: s34, s_A: 33, s_B: 1}
  - {name: s36, s_A: 35, s_B: 1}
  - {name: s38, s_A: 37, s_B: 1}
  - {name: s40, s_A: 39, s_B: 1}
  - {name: s42, s_A: 41, s_B: 1}
  - {name: s44, s_A: 43, s_B: 1}
  - {name: s46, s_A: 45, s_B: 1}
  - {name: s48, s_A: 47, s_B: 1}
  - {name: s50, s_A: 49, s_B: 1}
